### Configuration File for CIBR-FLARE Project
## General Settings
git:
  remote:
    server: github.com
    branch: master
    ssh-key-private: /root/.ssh/id_rsa
    user-name: Jyuqi
    user-email: jinyuqi@ufl.edu
## Container Settings
container:
  name: flare-generate-forecast
  version: 21.01.2
  working-directory:
    pre-run-pull: FALSE
    post-run-push: FALSE
    git:
      remote:
        server: 192.168.20.20
        port:
        repository: FLARE-forecast/test-data
        branch: master
        directory: fcre
## Container Paths
flare_path: /root/flare
flare_shared_path: /root/flare/shared
qaqc_data_location: /root/flare/shared/flare-process-observations/fcre-processed-observations
data_location: /root/flare/shared/flare-download-observations
noaa_location: /root/flare/shared/flare-process-noaa
lakes_directory: flare_lake_examples
forecast_location: /root/flare/shared/flare-generate-forecast/forecast
execute_location: /root/flare/shared/flare-generate-forecast/working_directory
run_config: /root/flare/shared/flare-generate-forecast/forecast/configuration_files/run_configuration.yml
##########################
# Lake information
###########################

lake_name_code: fcre
lake_name: Falling Creek Reservoir
lake_latitude: 37.307   #Degrees North
lake_longitude: 79.837  #Degrees West

#Time zone that GLM is run in
#Currently needed to be GMT so that it interfaces with the NOAA forecast
#reference_tzone <<- "GMT"
#Local time zone of the lake
local_tzone: "EST"

##########################
#  Information required to generate EML metadata file
##########################

metadata:
    forecast_project_id: test
    generate_eml: TRUE
    abstract: "This is where a longer description of the forest can be added"
    forecast_title: FLARE
    intellectualRights: insert license
    model_description:
        forecast_model_id: https://github.com/rqthomas/flare/commit/d1ddcb07b9d28863890597503fc4aa4a4496de56
        name: General Lake Model
        type: process-based
        repository: https://github.com/AquaticEcoDynamics/GLM/releases/tag/v3.1.0
    me:
        individualName:
              givenName: "Quinn"
              surName: "Thomas"
        electronicMailAddress:  "INSERT"
        id: INSERT ORCID



############################
# Run information
#############################

model_name: glm_aed #other is "null"

base_GLM_nml: configuration_files/glm3.nml

#All sources of uncertainty and data used to constrain
use_obs_constraint: TRUE
observation_uncertainty: TRUE
process_uncertainty: TRUE
weather_uncertainty: TRUE
initial_condition_uncertainty: TRUE
parameter_uncertainty: TRUE
met_downscale_uncertainty: TRUE
inflow_process_uncertainty: TRUE

specified_inflow1: FCR_weir_inflow_2013_2019_20200624_allfractions_2poolsDOC.csv
specified_outflow1: FCR_spillway_outflow_SUMMED_WeirWetland_2013_2019_20200615.csv

use_future_inflow: TRUE
future_inflow_flow_coeff: [0.0010803, 0.9478724, 0.3478991]
future_inflow_flow_error: 0.00965
future_inflow_temp_coeff: [0.20291, 0.94214, 0.04278]
future_inflow_temp_error: 0.943

forecast_met_model: NOAAGEFS_1hr
forecast_inflow_model: FLOWS-NOAAGEFS-AR1
#########################
### Depth information
#########################
#Depths used in the EnKF
#This are the depths that are saved between days
#Init depth of lake
lake_depth_init: 9.4  #not a modeled state

modeled_depths: [0.10, 0.33, 0.67,
                1.00, 1.33, 1.67,
                2.00, 2.33, 2.67,
                3.00, 3.33, 3.67,
                4.00, 4.33, 4.67,
                5.00, 5.33, 5.67,
                6.00, 6.33, 6.67,
                7.00, 7.33, 7.67,
                8.00, 8.33, 8.67,
                9.00]

default_temp_init: [25.667, 24.9101, 23.067, 21.8815, 19.6658, 16.5739, 12.9292, 12.8456, 12.8127, 12.8079, 12.778]
default_temp_init_depths: [0.127, 1.004, 2.005, 3.021, 4.002, 5.004, 6.004, 7.01, 8.001, 9.015, 9.518]
the_sals_init: 0.0

default_snow_thickness_init: 0.0
default_white_ice_thickness_init: 0.0
default_blue_ice_thickness_init: 0.0

#########
#  Management
########

simulate_sss: TRUE
sss_depth: 8.0
use_specified_sss: TRUE
specified_sss_inflow_file: .na
specified_sss_outflow_file: .na
forecast_sss_flow: 1000
forecast_sss_oxy: 500
#umol/m3  of oxygen if SSS turned on in forecast
sss_fname: manual-data/FCR_SSS_inflow_2013_2020.csv
sss_inflow_factor: 0.25



##############################
##  EnKF setup
##############################
ensemble_size:  221 #221 #441
localization_distance: .na #distance in meters were covariances in the model error are used
vert_decorr_length: 5.0
no_negative_states: TRUE
assimilate_first_step: FALSE

#################################
# Parameter calibration information
#################################

par_file: parameter_calibration_config.csv

#####################################
###  Observation information
######################################

obs_config_file: observations_config.csv

#########################################
###  State information
#########################################

states_config_file: states_config.csv
states_config_process_error: states_process_error.csv

#carbon to chlorophyll ratio (mg C/mg chla)
#12 g/ mole of C vs. X g/ mole of chla
#Initial concentration of phytoplankton (mmol C/m3)
# biomass_to_chla <<- c((160/12),(60/12), (60/12))

########################################
# Dignostics
#######################################

diagnostics_names:  [extc_coef]

## Openwhisk Settings
openwhisk:
  days-look-back: 1
  container-dependencies: "flare-process-noaa flare-process-observations flare-download-observations"
  next-trigger:
    name: flare-forecast-ready-fcre
    payload: '{"type":"payload", "FLARE_VERSION":"21.01.2", "container_name":"flare-visualize", "lake":"fcre", "s3_access_key":"root", "s3_secret_key":"y7S93S1bP8Y8", "openwhisk_apihost": "js-129-114-16-129.jetstream-cloud.org", "openwhisk_auth":"f8b8cbca-1f92-46d5-a6e4-934854364cac:3V788bmMBKSdDuSkwjDiTnzhY4wxj1Juy7ys46F6wu5dAV0sMOpUa5L42BvBPkbw", "ssh_key":["-----BEGIN RSA PRIVATE KEY-----","MIIJJwIBAAKCAgEAwUcArjhUsg5IgN0lKUgaSB2yomKJjhTLupTj+aPpttC2ILsP","aoyAtWDnZgvKhqfLGCvByLphlMzO8QAT+lxlfhpjJzUSoNGYSIFaDcL4xqp8CYgz","PuEU/qCOWoWSA6mCNTYNaxhUhWgrduZXJCL3HVLIXR5EN8798u64KATFHcBTe+PF","hKu3NBRUu5CiJz5Xg6BsmP/Ir/+TtgTStKJjz5C3ZDC7oGpIjvfra4F9hvuZ3KPX","7bqeQoR/LqmkjniGpNfOGEPCVYfMNTddLRw6/f/KP2DzVGmBKVhnZsSySsTZhPGm","7CjQDD87QUIefDwzUYZ+6IeXeWGB8Ybm2TkCAhbP6XIGop8jq1YXgxoFl8c0fctD","hup1BADYjAnVHdfuB3QrR6EEC8kgDAqOZHzrIsmBdwnngp8v74Fr0lEyFz1vlwxO","aR/sHdT+c69Nso7qjV/Yeny2CmXvKXTK1wVDmUIy+Hhlh/bh4e974MGGvqKtPOjC","3i4zTJjJSzvlBhdsS6djlIb/baiiN7iaCdiR2dkQYOnYsGW0tqBtb96abW2e9PpM","HUq8f7Wc12+rdOMnjgKuk/kP2ZfW9O7NXOSamyAz2EVE6SoTsIDuJMFEKNrYhczU","SvY8XImRLLFXxPk9sWfRo1WtfwQ9lfg2Azf2ZMuhO75PkpqsJTebSyyQLB8CAwEA","AQKCAgAxIe+WWlONf/wGZjFQMTgdJQ+IICx/peG0aK0bhQOgqaXi5CqjF1yQvzWT","x2OQn48NcfItKNQtk3L36OErP9m9GNAj42X848smg1t1LB85wZUOh0UfsvA3WnFV","qabYr3qeNENs+h5iW3zRGPUGBq1zEtxEb7E/zqrX2r+NzMifK4kNcXWAqHZGEvUH","SVkvSLXOjDWPH1bRBtNx7f/yU2W0GkHEgm7v9JTFY1jBV4WljsgqQqxdjpc0qaH7","JrziStlPhlyp5m+8dmz/Cjfxg7+rWh77xZWV28wtyn9erJn2T9xL43JfjnB07I4P","pNNDGbqh+uLAEdf7z0HNOFHu3oMXu5OndXkHBCZOD5j0Oqm4mibtVltG1m/Z9+WT","V592Z2KrBivx2W4V8y0Z9ssY8xRu099btSQyfvrPcNRK8VTmq9J17HbrsAHhFzpm","rS/61NIPd+rkkz4Tf9eU85fe/sPTC0y+ezR2dfHG6VZ5NfPX9bycd0jS7s5H9fuu","eeKF3iG+6mDM2sGHsJXayQKuX276RKGIvQ2ikquLV3TLHvAfdpClrHNDaowUOhi1","94tP4qDBqeD3H047qn7hTMWeDu/5OWfqpiEccLdWSNxcGulGIMyByIw/DTb3cigD","TwV4RPHYsPx+pomWWn0TBB75OIYcKLaX5Uh1hMTtKn+CT3qSwQKCAQEA69EXJ1bd","ZuSXw/lCezTDySVm1Ud5TZSk57Lj2kAIqX6HsL7+e7ZmNpTjkd0kA/I+XjLIab7k","aVoPsihriEAMl0ygocgijFV4gvozqq32FfOE/bqRw+uiM3xwoMpde4FSQxBU1ipQ","FIOelu1mjY0oI+E4QP2NQJ1kcmrsr2B6Hmw6nMKQKElFpqRBksodr90kxbWl2FKj","tMaNxq6Trsp6iwnbi08Sx7Ae3pT0FerUERSgFz1CPKAmeRs48v8u8saTHuqJRWuD","PoxExBQTyIAWceAP5UozMbhQB6YRYBR2ez7gNWBrUIL1HEiAqpNYX5q71l5zeIe9","LFda+XTKY/MCKQKCAQEA0dHYHRKJVcph+GkOt45Vr0TBkRycbh8+V2rwcyZ6D/59","ee1cbKopFlaWnhump5pE2jejrWAAz+g3CI1oit5fdYAtcYS8muDwiTg4R6QZlD3V","4/SJLE2nOvHB0IwVID4KCYatGZydM84djw3qbknkh/JG2rSAkZ2rmmtU0DyDmnlC","Nha7yYAXYT0Iqn3gcr/9nB28oHQrS7ohLs96N2JSDWvqFsW5mMDLsYXjtyiyTuYO","RWLr0tmedO3UwlpGdeJpV/7QCymR5o3EXdkw4hB02C5TSJ9N5T7UX4GsJJDygQk9","szE9YemeT6gq+11/xCV/y3vvXa9T5/5XUBZyyQfVBwKCAQA7IEHd6zm4ArjKukSg","/6nXVTljYHhZq1ttfL0Ei+mgFcmP11OXUTRvmwU0HW5aTvK0S6dUXDiI8bvdv6S2","lNiTVvMvnS6MYSHGNVWfBd8dweEmfRDvPrV8k0bqCdNGlDY7+mxLBnDts9KfpQaB","l1LpLB8erHQuL0hwJ78QefAkkJ5hj6b1cumzzptiYqru3VPK/rCGfLHvMZl6p2r/","+GShV+dkFn9u8gnLZS2OEUL6xWEeco2ZBc6fruOoibMLzB43MjcY4MwXcrQLNb2A","GB2Ij9VseB496Sinwku4+2h5nlo5B+PgW/V5EfSw0CDoV7OhHC13mxEjfQOiaFYW","mWeBAoIBACm5ynmVmxwlgDAvbE7SjnWpfbkG8JDxw6sMyD6OE04k9P0PWAcAG+Wm","WJOeuhiwlCq1T+aFpgOykWcw/+5F5MPwNplRpVRDkXIobQDKQI/7cBLCKZlW4//T","3hBEG1trGwHj936VZ6nKvpQZV1qRdVIXu0F5DexnZ53w5E/5CM7qeGFbSgL7Zyre","QV/uYnlPdvbZ7w4VrBqGLF0rw4lKEzk6EbZvocYf6SInly5weG06UPI5ht5KirmE","JoB0BXkiCoMGWIcvwCUSYk+rho4eaa4oIEXb8Fi7ku5fUkV/UcqZdNyy2Rsko2gB","8HJGmMcAEhb8UZDW8h+7s89od3FFDncCggEAPxKnpXnMH5Ec5F9dGDpeUy4+EtPm","nPdFolvM6Yscef5ojW0ZxRMAqUZb3daVoQPWky7Qr+A0u9Ga8RF0r9PnB7ydi1O4","Se/tpNgQuVjn43UQoTr31j5S1NmREwANABWHjy1WJHshMNmtSGAUjjBTFu4oOmVy","FZ6wB/kLIykmKVShe328bNYzncQJ9HLgYSJpObb2McSvfo050YlZv+hSac3EpRec","jPlc6OcB+c8Ti5oswcQ4LG5zrE+aVoxx+ZoWnl25+6nzKbyc29p8dgbCw6OX0D65","QD9wUg3voFsQKlH9Sk11bp6tiOC7r6X/mEvRfhRT0xN9ZBtDjo7FXU26QQ==","-----END RSA PRIVATE KEY-----"]}'