version: "2"

services:
  web:
    build: 
          context: ../
          dockerfile: flare-download-observations/Dockerfile
    command: npm run dev
    ports:
      - "8080:8080"
      - "5858:5858"
    user: user
