### Configuration File for CIBR-FLARE Project
## General Settings
git:
  remote:
    server: github.com
    branch: master
    ssh-key-private: /root/.ssh/id_rsa
    user-name: Jyuqi
    user-email: jinyuqi@ufl.edu
## Container Settings
container:
  name: flare-download-observations
  version: 21.01.2
  working-directory:
    pre-run-pull: FALSE
    post-run-push: FALSE
    git:
      remote:
        server: 192.168.20.20
        port:
        repository: FLARE-forecast/test-data
        branch: master
        directory: fcre
        ssh-key-private:
        user-name:
        user-email:
## Parameters
lake_name_code: fcre
lake_name: Falling Creek Reservoir
noaa_location: flare-download-noaa-dev/fcre
realtime_insitu_location:
  git:
    remote:
      server: github.com
      repository: FLARE-forecast/FCRE-data
      branch: fcre-catwalk-data
      directory:
realtime_met_station_location:
  git:
    remote:
      server: github.com
      repository: FLARE-forecast/FCRE-data
      branch: fcre-metstation-data
      directory:
manual_data_location:
  git:
    remote:
      server: github.com
      repository: FLARE-forecast/FCRE-data
      branch: fcre-manual-data
      directory:
  manual-downloads:
  - url: https://portal.edirepository.org/nis/dataviewer?packageid=edi.389.4&entityid=c1db8816742823eba86696b29f106d0f
    file-name: Met_final_2015_2019.csv
realtime_inflow_data_location:
  git:
    remote:
      server: github.com
      repository: FLARE-forecast/FCRE-data
      branch: fcre-weir-data
      directory:

## Openwhisk Settings
openwhisk:
  days-look-back: 1
  container-dependencies: ""
  next-trigger:
    # name: flare-download-observations-ready-fcre
    name: events
    payload: '{"type":"payload", "FLARE_VERSION":"21.01.2", "container_name":"flare-download-observations", "lake":"fcre", "s3_access_key":"root", "s3_secret_key":"y7S93S1bP8Y8", "openwhisk_apihost": "js-129-114-16-129.jetstream-cloud.org", "openwhisk_auth":"f8b8cbca-1f92-46d5-a6e4-934854364cac:3V788bmMBKSdDuSkwjDiTnzhY4wxj1Juy7ys46F6wu5dAV0sMOpUa5L42BvBPkbw", "ssh_key":["-----BEGIN RSA PRIVATE KEY-----","MIIJJwIBAAKCAgEAwUcArjhUsg5IgN0lKUgaSB2yomKJjhTLupTj+aPpttC2ILsP","aoyAtWDnZgvKhqfLGCvByLphlMzO8QAT+lxlfhpjJzUSoNGYSIFaDcL4xqp8CYgz","PuEU/qCOWoWSA6mCNTYNaxhUhWgrduZXJCL3HVLIXR5EN8798u64KATFHcBTe+PF","hKu3NBRUu5CiJz5Xg6BsmP/Ir/+TtgTStKJjz5C3ZDC7oGpIjvfra4F9hvuZ3KPX","7bqeQoR/LqmkjniGpNfOGEPCVYfMNTddLRw6/f/KP2DzVGmBKVhnZsSySsTZhPGm","7CjQDD87QUIefDwzUYZ+6IeXeWGB8Ybm2TkCAhbP6XIGop8jq1YXgxoFl8c0fctD","hup1BADYjAnVHdfuB3QrR6EEC8kgDAqOZHzrIsmBdwnngp8v74Fr0lEyFz1vlwxO","aR/sHdT+c69Nso7qjV/Yeny2CmXvKXTK1wVDmUIy+Hhlh/bh4e974MGGvqKtPOjC","3i4zTJjJSzvlBhdsS6djlIb/baiiN7iaCdiR2dkQYOnYsGW0tqBtb96abW2e9PpM","HUq8f7Wc12+rdOMnjgKuk/kP2ZfW9O7NXOSamyAz2EVE6SoTsIDuJMFEKNrYhczU","SvY8XImRLLFXxPk9sWfRo1WtfwQ9lfg2Azf2ZMuhO75PkpqsJTebSyyQLB8CAwEA","AQKCAgAxIe+WWlONf/wGZjFQMTgdJQ+IICx/peG0aK0bhQOgqaXi5CqjF1yQvzWT","x2OQn48NcfItKNQtk3L36OErP9m9GNAj42X848smg1t1LB85wZUOh0UfsvA3WnFV","qabYr3qeNENs+h5iW3zRGPUGBq1zEtxEb7E/zqrX2r+NzMifK4kNcXWAqHZGEvUH","SVkvSLXOjDWPH1bRBtNx7f/yU2W0GkHEgm7v9JTFY1jBV4WljsgqQqxdjpc0qaH7","JrziStlPhlyp5m+8dmz/Cjfxg7+rWh77xZWV28wtyn9erJn2T9xL43JfjnB07I4P","pNNDGbqh+uLAEdf7z0HNOFHu3oMXu5OndXkHBCZOD5j0Oqm4mibtVltG1m/Z9+WT","V592Z2KrBivx2W4V8y0Z9ssY8xRu099btSQyfvrPcNRK8VTmq9J17HbrsAHhFzpm","rS/61NIPd+rkkz4Tf9eU85fe/sPTC0y+ezR2dfHG6VZ5NfPX9bycd0jS7s5H9fuu","eeKF3iG+6mDM2sGHsJXayQKuX276RKGIvQ2ikquLV3TLHvAfdpClrHNDaowUOhi1","94tP4qDBqeD3H047qn7hTMWeDu/5OWfqpiEccLdWSNxcGulGIMyByIw/DTb3cigD","TwV4RPHYsPx+pomWWn0TBB75OIYcKLaX5Uh1hMTtKn+CT3qSwQKCAQEA69EXJ1bd","ZuSXw/lCezTDySVm1Ud5TZSk57Lj2kAIqX6HsL7+e7ZmNpTjkd0kA/I+XjLIab7k","aVoPsihriEAMl0ygocgijFV4gvozqq32FfOE/bqRw+uiM3xwoMpde4FSQxBU1ipQ","FIOelu1mjY0oI+E4QP2NQJ1kcmrsr2B6Hmw6nMKQKElFpqRBksodr90kxbWl2FKj","tMaNxq6Trsp6iwnbi08Sx7Ae3pT0FerUERSgFz1CPKAmeRs48v8u8saTHuqJRWuD","PoxExBQTyIAWceAP5UozMbhQB6YRYBR2ez7gNWBrUIL1HEiAqpNYX5q71l5zeIe9","LFda+XTKY/MCKQKCAQEA0dHYHRKJVcph+GkOt45Vr0TBkRycbh8+V2rwcyZ6D/59","ee1cbKopFlaWnhump5pE2jejrWAAz+g3CI1oit5fdYAtcYS8muDwiTg4R6QZlD3V","4/SJLE2nOvHB0IwVID4KCYatGZydM84djw3qbknkh/JG2rSAkZ2rmmtU0DyDmnlC","Nha7yYAXYT0Iqn3gcr/9nB28oHQrS7ohLs96N2JSDWvqFsW5mMDLsYXjtyiyTuYO","RWLr0tmedO3UwlpGdeJpV/7QCymR5o3EXdkw4hB02C5TSJ9N5T7UX4GsJJDygQk9","szE9YemeT6gq+11/xCV/y3vvXa9T5/5XUBZyyQfVBwKCAQA7IEHd6zm4ArjKukSg","/6nXVTljYHhZq1ttfL0Ei+mgFcmP11OXUTRvmwU0HW5aTvK0S6dUXDiI8bvdv6S2","lNiTVvMvnS6MYSHGNVWfBd8dweEmfRDvPrV8k0bqCdNGlDY7+mxLBnDts9KfpQaB","l1LpLB8erHQuL0hwJ78QefAkkJ5hj6b1cumzzptiYqru3VPK/rCGfLHvMZl6p2r/","+GShV+dkFn9u8gnLZS2OEUL6xWEeco2ZBc6fruOoibMLzB43MjcY4MwXcrQLNb2A","GB2Ij9VseB496Sinwku4+2h5nlo5B+PgW/V5EfSw0CDoV7OhHC13mxEjfQOiaFYW","mWeBAoIBACm5ynmVmxwlgDAvbE7SjnWpfbkG8JDxw6sMyD6OE04k9P0PWAcAG+Wm","WJOeuhiwlCq1T+aFpgOykWcw/+5F5MPwNplRpVRDkXIobQDKQI/7cBLCKZlW4//T","3hBEG1trGwHj936VZ6nKvpQZV1qRdVIXu0F5DexnZ53w5E/5CM7qeGFbSgL7Zyre","QV/uYnlPdvbZ7w4VrBqGLF0rw4lKEzk6EbZvocYf6SInly5weG06UPI5ht5KirmE","JoB0BXkiCoMGWIcvwCUSYk+rho4eaa4oIEXb8Fi7ku5fUkV/UcqZdNyy2Rsko2gB","8HJGmMcAEhb8UZDW8h+7s89od3FFDncCggEAPxKnpXnMH5Ec5F9dGDpeUy4+EtPm","nPdFolvM6Yscef5ojW0ZxRMAqUZb3daVoQPWky7Qr+A0u9Ga8RF0r9PnB7ydi1O4","Se/tpNgQuVjn43UQoTr31j5S1NmREwANABWHjy1WJHshMNmtSGAUjjBTFu4oOmVy","FZ6wB/kLIykmKVShe328bNYzncQJ9HLgYSJpObb2McSvfo050YlZv+hSac3EpRec","jPlc6OcB+c8Ti5oswcQ4LG5zrE+aVoxx+ZoWnl25+6nzKbyc29p8dgbCw6OX0D65","QD9wUg3voFsQKlH9Sk11bp6tiOC7r6X/mEvRfhRT0xN9ZBtDjo7FXU26QQ==","-----END RSA PRIVATE KEY-----"]}'